AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    study-datalake

    Rest API to manage a Data Lake of study links

Globals:
    Function:
        Timeout: 20
        MemorySize: 512
        Environment:
          Variables:
            TABLE_NAME: !Ref TripTable
            ENDPOINT_OVERRIDE: ""

Resources:

  CreateTripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/study-datalake-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.CreateStudyRecord::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       CreateTripRecord:
         Type: Api
         Properties:
           Path: /trips
           Method: post
           
  GetTripSByCountryFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/study-datalake-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.GetStudyRecordsByPeriod::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       GetTripSByCountry:
         Type: Api
         Properties:
           Path: /trips/{country}/findByCountry
           Method: get
           RequestParameters:
              - method.request.querystring.country             
  GetTripSByCityFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/study-datalake-1.0.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.iwe.handler.GetStudyRecordsByTag::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       GetTripSByCity:
         Type: Api
         Properties:
           Path: /trips/{country}/findByCity
           Method: get
           RequestParameters:
              - method.request.querystring.country
              - method.request.querystring.city             
  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
        - AttributeName: country
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: reason
          AttributeType: S            
      KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: city
          KeyType: RANGE
      LocalSecondaryIndexes: 
        - IndexName: cityIndex
          KeySchema: 
            - AttributeName: country
              KeyType: HASH
            - AttributeName: city
              KeyType: RANGE
          Projection:
             ProjectionType: ALL 
      BillingMode: PAY_PER_REQUEST              

Outputs:

    CreateTripRecordFunction:
      Description: "CreateTripRecord Lambda Function ARN"
      Value: !GetAtt CreateTripRecordFunction.Arn
      
    GetTripSByCountryFunction:
      Description: "GetTripSByCountry Lambda Function ARN"
      Value: !GetAtt GetTripSByCountryFunction.Arn
      
    GetTripSByCityFunction:
      Description: "GetTripSByCity Lambda Function ARN"
      Value: !GetAtt GetTripSByCityFunction.Arn
           